trigger:
- Master

pool:
  vmImage: ubuntu-latest

variables:
- group: New variable group 14-Jan
- group: ACR_CRED

steps:
- task: Bash@3
  displayName: 'Build docker image'
  inputs:
    filePath: 'build.sh'
  env:
    D_USERNAME: $(ACR_USERNAME)
    D_PASSWORD: $(ACR_PASSWORD)
    BUILD_ID: $(Build.BuildNumber)
